image: python:alpine

cache:
  key: pip_cache
  paths:
    - .pip_cache/

before_script:
  - pip --cache=$CI_PROJECT_DIR/.pip_cache install -e .[test]

test:
  script:
    - flake8 src test
    - pytest
